{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\src}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\jpeg\$(TargetCPU)-$(TargetOS)}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\msvcrt\$(TargetCPU)}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\ogg\$(TargetCPU)-$(TargetOS)}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\theora\$(TargetCPU)-$(TargetOS)}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\zlib\$(TargetCPU)-$(TargetOS)}
{$UNITPATH ..\..\ZenGL\zengl-src-0.3.0rc2\lib\zip\$(TargetCPU)-$(TargetOS)}

